# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jerry_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jerry(object):
    def setupUi(self, Jerry):
        Jerry.setObjectName("Jerry")
        Jerry.resize(1344, 832)
        self.centralwidget = QtWidgets.QWidget(Jerry)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1341, 831))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("jerry.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 430, 241, 251))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("open.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1090, 760, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1210, 760, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 40, 291, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1010, 40, 291, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")
        Jerry.setCentralWidget(self.centralwidget)

        self.retranslateUi(Jerry)
        QtCore.QMetaObject.connectSlotsByName(Jerry)

    def retranslateUi(self, Jerry):
        _translate = QtCore.QCoreApplication.translate
        Jerry.setWindowTitle(_translate("Jerry", "MainWindow"))
        self.pushButton.setText(_translate("Jerry", "RUN"))
        self.pushButton_2.setText(_translate("Jerry", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jerry = QtWidgets.QMainWindow()
    ui = Ui_Jerry()
    ui.setupUi(Jerry)
    Jerry.show()
    sys.exit(app.exec_())
